name: Build All Exercises JSON

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build merged JSON
        run: node build.js

      - name: Commit result
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add all_exercises.json
          git commit -m "update merged exercises json" || echo "No changes"
          git push
